### ISSUE TITLE
JS code should not be part of the repository

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#116]
./gutenbergtozim/templates/datatables/DataTables-1.10.13/js
./gutenbergtozim/templates/datatables/Responsive-2.1.1/js

**Comment by hksingh4545** [comment]
I want to work on this. Can you elaborate a little more about the issue?

**Comment by satyamtg** [comment]
@hksingh4545 sure, all you need to do is to remove those javascript dependencies from this repository and in place of that, introduce functionality to download those when running the scraper. This is done in other scrapers by introducing a `get_js_deps.sh` In other scrapers. See - https://github.com/openzim/ted/blob/master/get_js_deps.sh . Hope that helps.

**Comment by RaghavS8Y** [comment]
Hi I would like to work on this issue!


Can you please guide me where can I get started?
