### ISSUE TITLE
Use python-libzim

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#136]
in place of zimwriterfs

**Comment by benoit74** [comment]
FYI, I'm also preparing a PR on this one, it is hard to test #156 while still relying on zimwriterfs + I already gained a significant experience on zimscraperlib ^^
Already have something working for JS files + authors HTML file, hopefully close to a first prototype (hardest part is probably around progress reporting)

**Comment by rgaudin** [comment]
Great! Maybe leave progress reporting for a second time? Switching to libzim would be a great achievement already
