### ISSUE TITLE
EPUB files and covers are no longer in the download as of 2022-02

### ISSUE THREAD

**Issue by jules2689** [openzim/gutenberg#147]
### EPUB

I've been looking at the gutenburg zim files and I've noticed that there is inconsistent availability for the epub files.

For example, `Pride and Prejudice` is not available in 2022-02:
- Book: https://library.kiwix.org/gutenberg_en_all_2022-02/A/Pride%20and%20Prejudice_cover.1342.html
- HTML (fine): https://library.kiwix.org/gutenberg_en_all_2022-02/A/Pride%20and%20Prejudice.1342.html
- EPUB (not found): https://library.kiwix.org/gutenberg_en_all_2022-02/I/Pride%20and%20Prejudice.1342.epub

However in 2022-01 EPUB works (I downloaded the old version and tried it out).

I continued testing other files and I could not find an epub that works in 2022-02. I found that most of the links worked in 2022-01, however it is important to note that some like `A Tale of Two Cities` was still not found in 2022-01.

If you look at the file size, 2022-02 is ~10GB less than 2022-01:

- [gutenberg_en_all_2022-01.zim](https://download.kiwix.org/zim/gutenberg/gutenberg_en_all_2022-01.zim)  `2022-01-12 08:41   64G`
- [gutenberg_en_all_2022-02.zim](https://download.kiwix.org/zim/gutenberg/gutenberg_en_all_2022-02.zim)  `2022-02-12 05:50   54G`

### Covers

2022-02 is also missing covers.

2022-02:
![2022-02 is missing covers](https://user-images.githubusercontent.com/3074765/155450185-e85f021c-0dfa-439d-9a1c-7e81147917f5.png)

2022-01:
![2022-01 has covers](https://user-images.githubusercontent.com/3074765/155450153-b2b96261-19ec-41b6-a225-63412b516d49.png)

**Comment by eshellman** [comment]
Is the harvester coming from 88.117.48.47 by any chance?

**Comment by kelson42** [comment]
@eshellman I have deleted your comment as IP informations are private.

**Comment by kelson42** [comment]
The log confirms that the EPUB can not be found:
```
$ grep -P '#1342[#./, ]{1}' 878b4a6d9463cffec1e56026_gutenberg.log 
[gutenbergtozim::2022-02-11 17:50:01,921] DEBUG:[epub] Requesting URLs for #1342# Pride and Prejudice
[gutenbergtozim::2022-02-11 17:50:02,248] ERROR:NO FILE FOR #1342/epub
[gutenbergtozim::2022-02-11 17:50:02,282] DEBUG:[pdf] Requesting URLs for #1342# Pride and Prejudice
[gutenbergtozim::2022-02-11 17:50:02,496] ERROR:NO FILE FOR #1342/pdf
[gutenbergtozim::2022-02-11 17:50:02,601] DEBUG:[html] Requesting URLs for #1342# Pride and Prejudice
[gutenbergtozim::2022-02-11 23:48:33,233] INFO:	Exporting Book #1342.
[gutenbergtozim::2022-02-11 23:48:33,234] WARNING:Missing HTML content for #1342 at dl-cache/1342/unoptimized/1342.html
[gutenbergtozim::2022-02-12 09:04:36,051] INFO:	Exporting Book #1342.
[gutenbergtozim::2022-02-12 09:04:36,051] WARNING:Missing HTML content for #1342 at dl-cache/1342/unoptimized/1342.html
```

**Comment by kelson42** [comment]
@rgaudin Any idea what is going on here?

**Comment by eshellman** [comment]
looks to me like an issue at the gutenberg mirror. I'm looking into it.

**Comment by kelson42** [comment]
@eshellman Thank you very much!

**Comment by eshellman** [comment]
the cache/epub/* tree no longer fits on aleph; use dante instead. https://www.gutenberg.org/dirs/MIRRORS.ALL
