### ISSUE TITLE
Provide localised title/description ZIM metadata

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#148]
Currently the Gutenberg ZIM we produce share the exact same ZIM title/description metadata (in English)

![image](https://user-images.githubusercontent.com/1029718/155838466-6022d6f4-3639-4c91-9bef-35d73ed52ffa.png)

This, although:
* we already have a UI translated in a few languages
* the scraper allows to customize it

I think we should either introduce translated versions of these metadata or split the recipe in Zimfarm https://farm.openzim.org/recipes/gutenberg_mul_all.

@rgaudin Not sure what is the best approach

**Comment by kelson42** [comment]
@rgaudin OK, it would be good that these two strings are besides the others.
@eshellman Any comment on this? You see in the screenshot how it is today? Do you have a source of translated strings which would be better?

**Comment by eshellman** [comment]
No, but I think the community could generate such a list in a few weeks.

**Comment by eshellman** [comment]
so the strings to be translates would be Title: "Project Gutenberg Library - Books in <language>" and Description: "The first producer of Free Ebooks" (or something better). ?

**Comment by kelson42** [comment]
Best handled with Translatewiki I guess.

**Comment by kelson42** [comment]
We just need here to have the strings in the translation files. Trivial.

**Comment by kelson42** [comment]
@rgaudin I want to fix this ASAP now. If I implement #56, does that will work out of the box?
