### ISSUE TITLE
Upgrade to PouchDb 8.0

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#154]
See https://pouchdb.com/2022/12/14/pouchdb-8.0.0.html

**Comment by theparthshukla** [comment]
Happy to take this up!

**Comment by rgaudin** [comment]
Please do

**Comment by theparthshukla** [comment]
Hey all, was looking into this ticket over the weekend and was a bit confused as I couldn't spot any usage or import of PouchDB in the project. Please pardon my ignorance on the off chance I may have missed something trivial as to my assumption, the scope of this task was for upgrading the PouchDB version

**Comment by rgaudin** [comment]
Indeed! Not sure why @kelson42 created this ticket. We'd want to use it at some point instead of those plain JS arrays and we use it in another project (nautilus) so he probably got confused.

Sorry for wasting your time 😕
