### ISSUE TITLE
Resolve CodeFactor issues on tools.js

### ISSUE THREAD

**Issue by benoit74** [openzim/gutenberg#158]
CodeFactor is currently complaining about many issues in `templates/js/tools.js`

Most of them should be fixed. Usually the only one which are tolerated are the "complex method" ones (which would need a massive revamping).

See e.g. https://github.com/openzim/gutenberg/pull/157/checks?check_run_id=10676559369

**Comment by theparthshukla** [comment]
Happy to take this up!
