### ISSUE TITLE
Replace « mul » ZIM « language » metadata in the multiple language ZiM

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#174]
With https://github.com/kiwix/libkiwix/issues/872#issuecomment-1441240397 we have decided to not use anymore this « special » ZIM language code. Instead we want to striclty respect the ZIM specification and put the list of languages in a comma separated string.

**Comment by rgaudin** [comment]
Although the spec doesn't mention anything, it's likely that readers will only display a couple languages at first sight with the rest in an extended view.

I would thus suggest to list the languages ordered by "importance" which we can set to number of entries for the moment.

**Comment by kelson42** [comment]
@rgaudin What woukd be the dfinition of "important"?

**Comment by rgaudin** [comment]
I wrote in my comment that we can consider nb of books for now

**Comment by kelson42** [comment]
@rgaudin LGTM, we can update the spec.

**Comment by kelson42** [comment]
@rgaudin Can we fix this quickly?

**Comment by kelson42** [comment]
[Specification updated](https://wiki.openzim.org/w/index.php?title=Metadata&type=revision&diff=31256&oldid=31251)
