### ISSUE TITLE
[REGRESSION] multilang ZIM filters broken

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#175]
Seems to me they are all broken since 2.0.0 release https://library.kiwix.org/viewer#gutenberg_mul_all_2023-02/Home.html

**Comment by benoit74** [comment]
Just to be sure, are we speaking about the combo box which shows only "All languages" ?

**Comment by kelson42** [comment]
Yes, filter by author as well and bookshelves are empty.

**Comment by rgaudin** [comment]
There are several JS errors in the console.

For instance there is template code in the generated JS file which is obviously gonna cause problems:

**`/js/l10n.js`**

```js
var available_languages = [{% for lang in ui_languages %} '{{ lang }}', {% endfor %}];
```

**Comment by benoit74** [comment]
Is this something which has been changed in 2.0 ? I do not remember to have touched this.

**Comment by kelson42** [comment]
Strongly suspect this is related to the "removal" of namespaces...
