### ISSUE TITLE
Release container build should be triggered on release event

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#176]
… but for now this is on tagging event.

**Comment by rgaudin** [comment]
- We don't handle container builds on release anywhere.
- Github release process is based on tags so it's equivalent
- We can't override a package submitted to PyPi but we can push (willingly or not) to the same image tag again so there is no guarantee that a tag matches a release. ➡️ We could manually add the image digest in the release note.
- it would complexify the docker publishing process without any clear advantage:
  - duplicate docker workflow code, both in release and in dev
  - what about test tags (for branches)?
  - additional conditions on workflow are a pain to debug

**Comment by kelson42** [comment]
> * We don't handle container builds on release anywhere.

Yes, we start now
 
> * Github release process is based on tags so it's equivalent

It's not, you can perfectly have a tag without a release.

The problem is that now we have a release process which is not atomic, one part runs first (on tagging) and one other part runs later (on release). This is confusing and actually pretty error prone.

**Comment by rgaudin** [comment]
> Yes, we start now

It would be **so much better** to introduce such changes in an overview ticket and pass it down instead of popping up in a random scraper without any justification.

**Comment by kelson42** [comment]
@rgaudin We had a discussion about this ticket. Does that still need anything else?
