### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#183]
From https://farm.openzim.org/pipeline/64d2c2a62c45ca437da64346/debug

```
Exception ignored in: <function MagicDetect.__del__ at 0x7f160ac26480>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/magic.py", line 308, in __del__
  File "/usr/local/lib/python3.11/site-packages/magic.py", line 135, in close
TypeError: 'NoneType' object is not callable

```

I wonder a bit the task has been successful

**Comment by rgaudin** [comment]
It is successful, as the log clearly states.

This is an _Ignored expection_ as indicated that we're not responsible for. It appears in many of our scrapers as it's from [magic](https://pypi.org/project/file-magic/#files), a scraperlib dependency. It's a silenced race condition on the magic database closing.

You should remember having seen this many times, in wikihow and elsewhere
