### ISSUE TITLE
Spanish file is not working properly

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/gutenberg#186]
This file
https://library.kiwix.org/viewer#gutenberg_es_all_2023-05
is not working properly.
I checked the recipe in zimfarm and it was cancelled
https://farm.openzim.org/recipes/gutenberg_mul_all

Can you check please?

**Comment by RavanJAltaie** [comment]
@kelson42 I wanted someone to check if there is anything wrong with the recipe.
I got a complaint from Spanish speaking person that the file is not working properly.
I checked, it looked fine to me but the file size is small and I checked the recipe and found it cancelled, that's why I needed some expert to look at them and let me know.

**Comment by kelson42** [comment]
@RavanJAltaie If you don't see or understand yourself what is wrong, from a user perspective, then I can't either. In particular without specific guidance.

Regarding the "canceling", this is something which has no impact on users, as here no zim files have been generated.
