### ISSUE TITLE
Downloads from dante HTTP mirror are failing

### ISSUE THREAD

**Issue by benoit74** [openzim/gutenberg#187]
I'm trying to run the scrapper on my dev machine (like I did before) and I do not achieve to download any file, I always get 403 errors.

One sample URL: https://dante.pglaf.org/cache/epub/21287/pg21287.epub (which was working on the Zimfarm on 11th of June)

It also looks like the Zimfarm has experienced issues recently with this scrapper, last run has even been canceled because it took too long to complete : https://farm.openzim.org/pipeline/6ace2571-0dd9-43d8-bdd7-3a620890f787

@eshellman : do you have any hint of what might be going on? Thanks in advance!

**Comment by eshellman** [comment]
will check

**Comment by eshellman** [comment]
use aleph.pglaf.org 
dante is retired.
