### ISSUE TITLE
keep search box centered as screen size increases/decreases

### ISSUE THREAD

**Issue by ashgrigas** [openzim/gutenberg#39]
Currently it goes to Left aligned as you drag the screen larger.

![screenshot 2014-10-28 14 50 25](https://cloud.githubusercontent.com/assets/9436824/4814950/5fae9cb0-5ed3-11e4-907e-6487733911ef.png)
![screenshot 2014-10-28 14 50 00](https://cloud.githubusercontent.com/assets/9436824/4814951/5fb22524-5ed3-11e4-9494-042d8449dd60.png)

**Comment by rgaudin** [comment]
Thanks for the report.

I am taking a quick look at years-old bug and I chose to fix the mentioned behavior differently: 

Filters (authors can be accompanied by language in case of multilang zim) are now always left-aligned except on small mobile screen where it take the whole width and thus appear centered.

Look at the screenshots and reopen if needed.
![screen shot 2017-04-05 at 16 08 59](https://cloud.githubusercontent.com/assets/57929/24714270/5051fa38-1a28-11e7-8cea-7a681d477a69.png)
![screen shot 2017-04-05 at 16 08 53](https://cloud.githubusercontent.com/assets/57929/24714271/5053ffd6-1a28-11e7-9698-fed84b762a75.png)
![screen shot 2017-04-05 at 16 08 48](https://cloud.githubusercontent.com/assets/57929/24714272/505c9128-1a28-11e7-99e4-04fbf43bfc8a.png)
