### ISSUE TITLE
Smarter download approach

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#50]
To download each book, gutenberg2zim tries a list of URL pattern where the book file(s) might be. We have no way to know, for sure, where the files are.

The reason behind this is that over time the Gutenberg project has chosen many different methodologies.

Therefore, to do download file, the script has a hardcoded list of potential URLs where to download the file(s) and the script just go through each of then until one suceeds.

Most of the time, the script makes more tha 4-5 tries before catching the right one. Each try cost time, 05-1 second.

That's why it would be nice to make a smart guess about which URL pattern in the list might better work, and a propose a method.

Each time a URL pattern has been proven successful for a book, then move it from one to the top of the list and always tires the list of pattern from the top to the end.

By doing so, we could have a far more faster download process.

**Comment by kelson42** [comment]
The problem is pretty acute, in 4 days, I have only downloaded 10000 books and needed to restart the process many times.

**Comment by kelson42** [comment]
For now, only readingroo is used, but the requests should also deal with other mirrors http://gutenberg.readingroo.ms/MIRRORS.ALL.utf8

**Comment by rgaudin** [comment]
Agrees. For the record, only 6 http mirrors are working:

* http://www.mirrorservice.org/sites/ftp.ibiblio.org/pub/docs/books/gutenberg/
* http://eremita.di.uminho.pt/gutenberg/
* http://mirror.its.dal.ca/gutenberg/
* http://gutenberg.mirrors.tds.net/pub/gutenberg.org
* http://mirrors.xmission.com/gutenberg/
* http://gutenberg.readingroo.ms/

**Comment by kelson42** [comment]
@rgaudin yes, if the list is clearly written in the source code, migth be easier - even for someone like me - to update it.

**Comment by rgaudin** [comment]
Eventually, there are only two complete mirrors.
Since those are not meant to be scraped completely, they have usage restrictions.
Second largest language (fr) with a few thousand books is usually crawled directly without trouble.

English with dozens of thousands of books raises usage limits. I believe the only viable solution for English (most of the whole project anyway) is to create a local mirror from `rsync://readingroo.ms/gutenberg` and use it.
We would need to add an option to copy/link from that location directly instead of HTTP requests

What do you think?

**Comment by kelson42** [comment]
@rgaudin Do we have an idea of the whole size?

**Comment by rgaudin** [comment]
Hum, it is apparently 764GB at the moment, so not really a good alternative.
Clever use of `--exclude` could drastically reduce its size but I believe effort should be put into our crawler's logic.

Easiest next step from here would be to pause & continue the download process when receiving `HTTP 429` status code.

@kelson42, do you agree?

**Comment by kelson42** [comment]
@rgaudin yes

**Comment by dattaz** [comment]
Maybe we can use a mix of rsync and http, by guessing the url locally: 
1. we get all files URL using rsync : rsync -a --list-only rsync.mirrorservice.org::gutenberg.org
2. Then we check from the list (from 1.) which is the good url
3. We get it from serveur using http.
