### ISSUE TITLE
Provide a categorization by genre

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#52]
Searching the gutenberg dim is hard, browsing it is impossible if you don't know what you are looking for. I therefore wonder whether it is possible to add genre buttons, like "Crime", "Fantasy", "Erotic literature" etc. Also, one idea could be to add toplists, best rated crime fiction, or most downloaded crime fiction etc. There are no summaries of the content of each book, and that would have been nice, but i guess that's impossible as such things are not present on the gutenberg homepage either. 

First reported at https://sourceforge.net/p/kiwix/feature-requests/988/

**Comment by rgaudin** [comment]
That's mostly what the bookshelves feature offers. closing.
