### ISSUE TITLE
Add translation for Spanish

### ISSUE THREAD

**Issue by dattaz** [openzim/gutenberg#63]
We want to have our interface for gutenberg project in Spanish.
File with strings to translate in json is here https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py and you should add you locale here : https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/export.py#L40

**Comment by chocomochi** [comment]
I could pick up this one!

**Comment by kelson42** [comment]
@chocomochi thx

**Comment by armando-femat** [comment]
I could help, but never have contributed to opensource so I will need some guidance :D
