### ISSUE TITLE
Add translation for Dutch

### ISSUE THREAD

**Issue by dattaz** [openzim/gutenberg#64]
We want to have our interface for gutenberg project in Dutch.
File with strings to translate in json is here https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py and you should add you locale here : https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/export.py#L40

**Comment by jhellingman** [comment]
I've translated the UI strings and created two pull requests to resolve this issue.

**Comment by dattaz** [comment]
Thanks you !
(One pull request is better but it's work ;))

**Comment by jhellingman** [comment]
You're welcome (did all the work in the github web interface, as I felt no need to clone to my machine, didn't see immediately how to add to the pull-request that way.)
