### ISSUE TITLE
Add translation for Finnish

### ISSUE THREAD

**Issue by dattaz** [openzim/gutenberg#65]
We want to have our interface for gutenberg project in Finnish.
File with strings to translate in json is here https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py and you should add you locale here : https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/export.py#L40

**Comment by kelson42** [comment]
We should interface this scraper with Translatewiki.

**Comment by kelson42** [comment]
Basically a duplicate of #56
