### ISSUE TITLE
Styrange usage()

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#70]
```
-y --wipe-db                    Do not wipe the DB during parse stage
```

I suspect that what is meant is:

```
-y --wipe-db                    Wipe the DB during parse stage
```

All in one this is not clear what does that mean. Which DB? What is the impact for the user to choose this option?

**Comment by dattaz** [comment]
This strange message is from https://github.com/openzim/gutenberg/commit/3fc8d3a039fbd1bed9cc9a460c5277916570306e which rename option from --keep-db to --wipe-db without updating message. 
For more context see https://github.com/openzim/gutenberg/issues/15
I think what @jtaylor351 propose ("Empty cached book metadata") is more clear. 
@kelson42 are you ok with this ? is this proposal clear enough for you ?

**Comment by kelson42** [comment]
@dattaz @jtaylor351 Thank you, looks good to me.
