### ISSUE TITLE
Some links to see images in HTML versions of some books do not work

### ISSUE THREAD

**Issue by mossroy** [openzim/gutenberg#79]
In gutenberg_fr_all_2018-10.zim, inside the HTML version of book "Le roman de la rose - Tome I", there are images and a link next to them "Voir image".
This link should probably show a larger version of the image, but it does not work (the URL is not found in the ZIM file).
I have this issue in both kiwix-js and kiwix-desktop, so I suspect it might be an issue in the ZIM file itself.

NB : this link does not seem to be in the EPUB version of the book. In the PDF version, clicking on the image leads to a bigger image at the end of the document

**Comment by kelson42** [comment]
We should probably check that as soon as we can with the most recent ZIM file.

**Comment by eshellman** [comment]
This is a book where the html links to bare image files. Adobe Digital Editions, for one, will not show the enlarged image-  it's not correct EPUB. Since the beginning of June, the PG ebookmaker makes wrapper html for linked images.like these.

**Comment by kelson42** [comment]
@eshellman Thx, so this is a problem upstream, nothing we can really do about :(

**Comment by rgaudin** [comment]
Good to know. @kelson42 should we close the ticket?

**Comment by kelson42** [comment]
I believe so.
