### ISSUE TITLE
Giant Downloads When Only Require Tiny Zim

### ISSUE THREAD

**Issue by nobicycle** [openzim/gutenberg#82]
Hello,

If I run the gutenberg2zim with -b to download a handful of books there is a stage where a large download occurs: 

> bash -c rsync -a --list-only rsync://aleph.gutenberg.org/gutenberg/ > tmp/file_on_aleph_gutenberg_org

On the first pass it downloaded a 250MB file. On the second pass it is at 30MB and counting ...

Is it possible to avoid this rsync stage?

Best wishes

**Comment by kelson42** [comment]
@rgaudin Do you know more?

**Comment by rgaudin** [comment]
I think it's mandatory. Haven't looked at code but I believe this sync is the base of the indexing of books (other options proved unreliable).

**Comment by nobicycle** [comment]
thanks
