### ISSUE TITLE
ePUB version missing from zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/gutenberg#83]
Most entries have an HTML and ePUB icon, and both seem clickable. The ePUB link, however, does not yield any file to download (tried both on Desktop 2.0 rc5 and macOS 2.0; zims were gutenberg_en_all_2018-10 and ale_all_2018-07.zim) - so either the scraper did not work properly, or ePubs were never meant to be included/read and therefore the logo should be removed as misleading.

![Capture d’écran 2019-07-25 à 16 24 40](https://user-images.githubusercontent.com/21675885/61882479-ec3c2d80-aef8-11e9-839a-59366e2b5ab2.png)

**Comment by kelson42** [comment]
@Popolechien I think Gutenberg project does not always provide an EPUB. Have you checked online with the original project for these files?

**Comment by rgaudin** [comment]
This is a reader(**s**) issue: not supporting downloading of file. It's been reported for macOS already ; I'll let you check for desktop (might have already been fixed by now?)
