### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [openzim/gutenberg#84]
In order to update ZIM files to the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your scraper:

* is using the lastest zimwriterfs (`1.3.5+` or `:latest` docker image). It supports new options and fixes important metadata (tags, favicon) and LZMA compression level.
* is including a `_category:gutenberg` tag (See [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317))
* is including a tag `gutenberg` tag
* is setting a proper `--name`.
* is using a proper `--flavour` (if relevant)
* is setting a `--scraper`.

**Comment by rgaudin** [comment]
done.

**Comment by kelson42** [comment]
Seems to fail, see http://library.kiwix.org/gutenberg_mul_all_2020-11/M/Tags. The tags don't have the new format.

**Comment by kelson42** [comment]
@rgaudin Or is that a problem at the zimfarm level? it seems impossible to configure the `--tags` in the Gutenberg recipe?

**Comment by rgaudin** [comment]
@kelson42 please be more explicit on tickets ; especially with a link on library which is frequently down.

Current Tags: `gutenberg;_ftindex:yes;_ftindex`

I checked the code and that's what we set. So we're only missing `_category:gutenberg`. Fixing that now.

And no, we can't set tags on gutenberg recipes as there is no need for that.
