### ISSUE TITLE
Search result page could be simplier

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#90]
This is how it looks like to me:
![screenshot](https://user-images.githubusercontent.com/1029718/65333831-7cc58000-dbc1-11e9-8928-78dd59f4487c.png)

To my opinion the icons on the right (both HTML and EPUB) stops us displaying many books because:
* Icons are superposed making the height of each item higher
* If the title is more than a few works then it will be displayed on many lines

I propose that under a certain width, these icon are not displayes, which means that you have first to click on the item to then get the choice between EPUB+HTML. By doing so, we will be able to have a more userfriendly search result page.

**Comment by rgaudin** [comment]
I suggest that under 400px width we keep only the HTML icon so that it's still easy to browse and take a peak while removing most of the clutter.

What do you think?

**Comment by kelson42** [comment]
We can try that first.... but this won't really solve the problem of to few places to display title properly on one line.

**Comment by rgaudin** [comment]
There are really long titles anyway and it was designed from the beginning to accomodate the title on multiple lines.

What bothers me with the current design is that the ratio useful info/space is not respected: getting EPUB and PDF is *mostly* used as downloads so it's OK to defer them to the article page.

HTML is different in that it's most probably what the user will want when selecting a content (by its title) so it's a useful shortcut.

It the titles were hardly readable, we surely should remove the icon completely but it's not the case, at least in your screenshot. Let me send screenshots of what I propose so we can decide.

**Comment by rgaudin** [comment]
![before](https://user-images.githubusercontent.com/57929/65350226-c23f7880-dbd4-11e9-9e3a-fa58126919f0.png)
![after](https://user-images.githubusercontent.com/57929/65350225-c1a6e200-dbd4-11e9-9f28-6b8d9c133d0a.png)

**Comment by kelson42** [comment]
@rgaudin Good to me. Thx!

**Comment by Popolechien** [comment]
Ok, I missed this, but is there an easier to understand icon? The "5" (I suspect it is but am not even sure) will only speak to the 0.001% of people on Earth who've ever heard of HTML.

**Comment by kelson42** [comment]
@Popolechien We all agree with you I believe... feel free to propose a new image in a dedicated ticket.

**Comment by rgaudin** [comment]
Agrees. Also, the HTML version here is used to be read-only so we don't care __at all__ about the format being HTML. Icon could represent the fact that it's for direct reading vs download.

**Comment by Popolechien** [comment]
Ok, we have designer coming over, I'll ask him about this.
