### ISSUE TITLE
project Gutenberg does not work 

### ISSUE THREAD

**Issue by mikejab** [openzim/gutenberg#92]
Hi 

I am running IOS 13.2 and kiwix 1.1 on XR 256gb

Downloaded Project Gutenberg 57.32 gb zim. 

When I try to download (red down arrow above cpu looking box) nothing happens. If I copy I get something like 
kiwix://b85a521d-ac99-2d25-1282-aa7456ecf9dd/I/Pride%20and%20Prejudice.1342.epub
But this is not openable. 

This is likely a substantial bug for the iOS version as I have done the following without change

Reinstalled IOS clean
Redownload zim multiple times
Tried on my wife’s XR phone. 
Installed most book reader apps 

I have reached out in the past but did not get assistance. 

Can you assist?

Mike
5123061509

Sent from my iPhone

**Comment by rgaudin** [comment]
Hi @mikejab, this is iOS-reader bug that should be opened at [/kiwix/apple](/kiwix/apple). I can't transfer it as it's a different org. @kelson42 ?

It seems that the kiwix reader for iOS doesn't support downloading.
